name: gui_app
dependencies:
        - python>=3.10
        - numpy
        - scipy
        - matplotlib
        - pip
        - pip:
                - git+https://github.com/ZBT-Tools/pemfc-core.git@master#egg=pemfc
                - git+https://github.com/ZBT-Tools/data-transfer.git@master#egg=data_transfer
