name: gui_app
dependencies:
        - python>=3.9.7
        - pip
        - numpy
        - scipy
        - matplotlib
        - pip:
                - git+https://github.com/ZBT-Tools/pemfc-core.git@master#egg=pemfc
